### ISSUE TITLE
Accents in slp1 not converted - sanscript

### ISSUE THREAD

**Issue by drdhaval2785** [indic-transliteration/indic_transliteration_py#33]
Udatta, anudatta and svarita are encoded as "/", "\\" and "^" respectively. 

Currently package is not transliterating them to their proper accent marks as far as I know.
I tried to convert `sA/raTi` from slp1 to devanagari. It gave `सा/रथि`.
It should be showing `सा॑रथि`.

**Comment by drdhaval2785** [comment]
@vvasuki any idea how to implement this accent thing? I am feeling the handicap in case of Vedic texts / dictionaries conversion.

**Comment by vvasuki** [comment]
I am unsure what symbol you refer to by svarita (unicode folks have screwed up there, and the mark you call udAtta actually seems to be svarita). :-)

Idea would be to add the symbols to DevanagariScheme.symbols , copy it to every other scheme (roman or brAhmic), except for slp1 where you put the transliterations. Then add a test and make sure it works fine.

**Comment by gasyoun** [comment]
> mark you call udAtta actually seems to be svarita

@drdhaval2785 where do we go from here?

**Comment by drdhaval2785** [comment]
I am not sure about the structure of the code, so did not make changes suggested by @vvasuki .

**Comment by vvasuki** [comment]
Add "/", "\" and "^" to a line after https://github.com/sanskrit-coders/indic_transliteration/blob/59ba0431caf5aff430eccb6d5f4b08d2da619882/indic_transliteration/sanscript/schemes/roman.py#L306 . Then in corresponding definitions of other schemes, add the corresponding svara-symbols (or devanAgarI equivalents if they're not defined.)

**Comment by drdhaval2785** [comment]
Thanks. Will give it a shot.

**Comment by vvasuki** [comment]
ऋग्वेदं दृष्ट्वा सार॑थिः इति प्रकृतिस्वरविन्यासो ज्ञायते। एवन्तर्हि SLP इत्यस्मिन् ‌/ इत्य् उदात्तस्यैव चिह्नं स्यात्। तथा सति, देवनागर्यां ꣡ इति चिह्नम् उचितम् ( https://groups.google.com/g/sanskrit-programmers/c/x_K7MZi5oKI इत्यत्रोक्तया रीत्या )। तदनुसारेण "/" इति चिह्नं निक्षिप्तम् अधुना। अन्ययोर् अर्थज्ञानाभावे न निवेशने चेष्टे। परिपूर्णसूचनायां लब्धायां सूत्रम् इदम् पुनर् उद्घाट्यताम्।

**Comment by vvasuki** [comment]
( https://github.com/indic-transliteration/common_maps/commit/1d32d19aa277a3b1610c54d0f93a742db76f6b3f इति परिवर्तितम्। )
