### ISSUE TITLE
handling missing characters like ऩ ऱ ऴ क़ ख़ ग़ ज़ ड़ ढ़ फ़ य़ in Telugu/Tamil/Malayalam

### ISSUE THREAD

**Issue by karthikraman** [indic-transliteration/indic_transliteration_py#52]
Some nice pointers by @vvasuki in https://github.com/sanskrit-coders/indic_transliteration/commit/caeb1b4547c1a74469ced4760541aba10f0bcaae#r45792167

**Comment by vvasuki** [comment]
Should be handled now.
