### ISSUE TITLE
saṃ vs. saṁ

### ISSUE THREAD

**Issue by gasyoun** [indic-transliteration/indic_transliteration_py#54]
Can we add non-standard `ṁ` additionally to `ṃ` to IAST?

https://github.com/kmadathil/sanskrit_parser/issues/165

**Comment by vvasuki** [comment]
You could add a new variant by creating a subclass of https://github.com/sanskrit-coders/indic_transliteration/blob/59ba0431caf5aff430eccb6d5f4b08d2da619882/indic_transliteration/sanscript/schemes/roman.py#L163 and overriding the appropriate dict value.

**Comment by gasyoun** [comment]
> You could add a new variant by creating a subclass of

I could, but could @kmadathil ?

**Comment by kmadathil** [comment]
Since this is legal  [ISO15919](https://en.wikipedia.org/wiki/ISO_15919), perhaps we can add an ISO15919 scheme instead?

**Comment by vvasuki** [comment]
> Since this is legal [ISO15919](https://en.wikipedia.org/wiki/ISO_15919), perhaps we can add an ISO15919 scheme instead?

Good idea - Go ahead.

**Comment by vvasuki** [comment]
ISO added.
