### ISSUE TITLE
Minor issue with .title()

### ISSUE THREAD

**Issue by karthikraman** [indic-transliteration/indic_transliteration_py#67]
An odd behaviour
```
>>> sanscript.transliterate('tRtIyA', sanscript.HK, sanscript.ISO).title()
>>> 'Tr̥Tīyā'
```
Is this a potential bug in `title()` --- thoughts?

**Comment by vvasuki** [comment]
Agree - reported at 10 year old bug at https://bugs.python.org/issue12737 , which seems to be on the way to resolution.
