### ISSUE TITLE
Please update the dependency requirements. 

### ISSUE THREAD

**Issue by KKM1983** [indic-transliteration/indic_transliteration_py#69]
Installation unnecessarily downgrades regex and other packages.
Regex updates are critical to do other crucial Unicode processing.

I manually recreated the wheel and removed the version requirements for regex and other packages.  and it worked fine.  Simpler to indicate a minimum version instead of forcing a very specific release.

**Comment by drdhaval2785** [comment]
A PR would be welcome.

**Comment by KKM1983** [comment]
I don't actively use GITHUB; summarizing my changes below.

In the file indic_transliteration-2.3.5.dist-info/METADATA  changed the == sign to >= and tested few of the statements on the home page. 

Requires-Dist: backports.functools-lru-cache (>=1.6.4)
Requires-Dist: selenium (>=3.141.0)
Requires-Dist: regex (>=2020.10.11)
Requires-Dist: typer (>=0.3.2)
