### ISSUE TITLE
Remove unused or heavy deps

### ISSUE THREAD

**Issue by akprasad** [indic-transliteration/indic_transliteration_py#74]
Not sure why `selenium` is a dependency for this package -- seems very heavyweight for a transliteration library.

Likewise, `aksharamukha` is already a transliterator so I'm curious what it's doing in this package.

**Comment by vvasuki** [comment]
> Not sure why `selenium` is a dependency for this package -- seems very heavyweight for a transliteration library.

Used in indic_transliteration/font_converter/tech_hindi/__init__.py . Some people used (rarely even today) non-unicode encodings. There is ready js/ html code which converts them - so wanted to invoke it from python. Seemed to be a good fit in a package dealing with conversion of text from one encoding (ie script) to another. Didn't seem worth it to have a separate package for just this bit.

> 
> Likewise, `aksharamukha` is already a transliterator so I'm curious what it's doing in this package.

There is a wrapper on aksharamukha at indic_transliteration/__init__.py which I found useful in many scripts (aksharamukha does a much superior job with certain scripts - like tamiL) - so placed it here. Ideally it should go to aksharamukha (if @virtualvinodh agrees to have a contrib module or the like, I'll move it there).

**Comment by akprasad** [comment]
ah, fair enough -- GitHub search implied the selenium usage was no longer in the repo https://github.com/indic-transliteration/indic_transliteration_py/blob/758507f6b899a5db4c28c376c08d3ec4be503665/indic_transliteration/font_converter/tech_hindi/__init__.py so I suppose that's a weakness of GitHub search.

I'll close this issue.
