### ISSUE TITLE
Double Svarita

### ISSUE THREAD

**Issue by TheRustyRhino** [indic-transliteration/indic_transliteration_py#76]
Is it possible to modify this project to support the ISO15919 standard? It better supports the hrasva e characters in languages like Telugu. Another issue is that the double svarita is not currently supported. Could this also be solved? Thank you very much!

**Comment by vvasuki** [comment]
> Is it possible to modify this project to support the ISO15919 standard? It better supports the hrasva e characters in languages like Telugu. 

Already supported - https://github.com/indic-transliteration/indic_transliteration_py/blob/b10ff37355bf8b009b3c0696e3d3819100e3c7e2/indic_transliteration/sanscript/__init__.py#L87 . Fixing documentation at the top of that file, which may be confusing.

> Another issue is that the double svarita is not currently supported. Could this also be solved? Thank you very much!

You're welcome to contribute a function which changes single svarita after a dIrgha-mAtrA to double-svarita.

**Comment by vvasuki** [comment]
> 
> You're welcome to contribute a function which changes single svarita after a dIrgha-mAtrA to double-svarita.

Did it myself with https://github.com/indic-transliteration/indic_transliteration_py/commit/a4ebd84da745b671021a31714c71d4ee1ec5b6c1
