### ISSUE TITLE
transliterate not working for this use case

### ISSUE THREAD

**Issue by NehaB18** [indic-transliteration/indic_transliteration_py#80]
Hello, I tired using transliterate on below message but it is not working. Could you please guide me for this use case.

```
from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate

# Given message
message = "ᗩᖇᗴ ᗷᗴᕼᗴᑎ ᗰᗴKO ՏᖇY ᗰՏT ᗷOᒪ ..ᗰᑌᒍᕼᗴ KᗩᗷᕼI ᗷᑌᖇᗩ ᑎᕼI ᒪᗩᘜTᗩ😂😂😂"

# Transliterate to Devanagari script (assuming the original script is Devanagari)
transliterated_message = transliterate(message, sanscript.ITRANS, sanscript.DEVANAGARI)

print(transliterated_message)
```

**Comment by vvasuki** [comment]
Input not ok 
![image](https://github.com/indic-transliteration/indic_transliteration_py/assets/2664797/6d12903a-f479-42f5-a006-cd81dffe51f6)


This software cannot handle it.

**Comment by drdhaval2785** [comment]
It is also not supposed to be handled.

**Comment by NehaB18** [comment]
Could you please point me what is the best way to handle this use case?

**Comment by drdhaval2785** [comment]
This is SMS lingo. Not in Devanagari / proper Hindi and not in proper script. So no transliteration machine will be able to help you.

Rough translation will be,
"O Sister, Don't say sorry to me. I never feel bad." 

In case you were looking for translation and not transliteration.
