### ISSUE TITLE
Duplicate projects?

### ISSUE THREAD

**Issue by tassa-yoniso-manasi-karoto** [indic-transliteration/indic_transliteration_py#84]
Hello,
I am looking from a library that can transliterate from living indic scripts/languages into the roman script.

I have found 3 python projects that all revolve around indic transliteration:

1. this repo
2. [libindic/indic-trans](https://github.com/libindic/indic-trans)
3. [virtualvinodh/aksharamukha](https://github.com/virtualvinodh/aksharamukha)

So I was wondering how they compare against one another.

I have seen you had made a pull request at aksharamukha and made that comment (#74) back in 2022:
> There is a wrapper on `aksharamukha at indic_transliteration/__init__.py` which I found useful in many scripts (aksharamukha does a much superior job with certain scripts - like tamiL) - so placed it here. Ideally it should go to aksharamukha (if @virtualvinodh agrees to have a contrib module or the like, I'll move it there).

So I guess you must be familiar with the other projects as well.

Is there some specific scripts/languages where aksharamukha or indic-trans still outperform this library? Or some useful feature that one lib has but the others don't?

@irshadbhat

**Comment by vvasuki** [comment]
aksharamukha is more thorough (handles more corner cases correctly).
Not familiar with indic-trans.

**Comment by tassa-yoniso-manasi-karoto** [comment]
Thanks, good to know.

So–out of curiosity–why do you keep working on this repo instead of forking aksharamukha and improving it further?

**Comment by vvasuki** [comment]
> So–out of curiosity–why do you keep working on this repo instead of forking aksharamukha and improving it further?

I'm more familiar with this code; it works fine for most indian languages, plus have control.
